---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 1/15/2019 7:49 PM
---

zRP.prepare("zRP/server_api_tables",[[
    CREATE TABLE IF NOT EXISTS zrp_srv_apis(
    dkey VARCHAR(100) PRIMARY KEY,
    dvalue LONGTEXT,
    last_time_update INTEGER,
    extra VARCHAR(100)
    );
]])

zRPBase.tables[12] = "zRP/server_api_tables"


zRP.prepare("zRP/set_srvapi","REPLACE INTO zrp_srv_apis(dkey,dvalue,last_time_update,extra) VALUES(@key,@value,@last_time_update,@extra)")
zRP.prepare("zRP/get_srvapi","SELECT dvalue FROM zrp_srv_apis WHERE dkey = @key")

