---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 2:42 PM
---
tzRP.table_data = {}

function tzRP.setClientTableData(tablename, msgpack)
    tzRP.table_data[tablename] = msgpack
end

function tzRP.getClienteTableData(tablename)
    return tzRP.table_data[tablename]
end