---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/30/2018 11:17 PM
---


-- this module define some police tools and functions

local handcuffed = false
local cop = false

-- set player as cop (true or false)
function tzRP.setCop(flag)
    cop = flag
    SetPedAsCop(GetPlayerPed(-1),flag)
end

-- HANDCUFF

function tzRP.toggleHandcuff()
    handcuffed = not handcuffed

    SetEnableHandcuffs(GetPlayerPed(-1), handcuffed)
    if handcuffed then
        tzRP.playAnim(true,{{"mp_arresting","idle",1}},true)
    else
        tzRP.stopAnim(true)
        SetPedStealthMovement(GetPlayerPed(-1),false,"")
    end
end

function tzRP.setHandcuffed(flag)
    if handcuffed ~= flag then
        tzRP.toggleHandcuff()
    end
end

function tzRP.isHandcuffed()
    return handcuffed
end

-- (experimental, based on experimental getNearestVehicle)
function tzRP.putInNearestVehicleAsPassenger(radius)
    local veh = tzRP.getNearestVehicle(radius)

    if IsEntityAVehicle(veh) then
        for i=1,math.max(GetVehicleMaxNumberOfPassengers(veh),3) do
            if IsVehicleSeatFree(veh,i) then
                SetPedIntoVehicle(GetPlayerPed(-1),veh,i)
                return true
            end
        end
    end

    return false
end

function tzRP.putInNetVehicleAsPassenger(net_veh)
    local veh = NetworkGetEntityFromNetworkId(net_veh)
    if IsEntityAVehicle(veh) then
        for i=1,GetVehicleMaxNumberOfPassengers(veh) do
            if IsVehicleSeatFree(veh,i) then
                SetPedIntoVehicle(GetPlayerPed(-1),veh,i)
                return true
            end
        end
    end
end

function tzRP.putInVehiclePositionAsPassenger(x,y,z)
    local veh = tzRP.getVehicleAtPosition(x,y,z)
    if IsEntityAVehicle(veh) then
        for i=1,GetVehicleMaxNumberOfPassengers(veh) do
            if IsVehicleSeatFree(veh,i) then
                SetPedIntoVehicle(GetPlayerPed(-1),veh,i)
                return true
            end
        end
    end
end

-- keep handcuffed animation
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(15000)
        if handcuffed then
            tzRP.playAnim(true,{{"mp_arresting","idle",1}},true)
        end
    end
end)

-- force stealth movement while handcuffed (prevent use of fist and slow the player)
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
        if handcuffed then
            SetPedStealthMovement(GetPlayerPed(-1),true,"")
            DisableControlAction(0,21,true) -- disable sprint
            DisableControlAction(0,24,true) -- disable attack
            DisableControlAction(0,25,true) -- disable aim
            DisableControlAction(0,47,true) -- disable weapon
            DisableControlAction(0,58,true) -- disable weapon
            DisableControlAction(0,263,true) -- disable melee
            DisableControlAction(0,264,true) -- disable melee
            DisableControlAction(0,257,true) -- disable melee
            DisableControlAction(0,140,true) -- disable melee
            DisableControlAction(0,141,true) -- disable melee
            DisableControlAction(0,142,true) -- disable melee
            DisableControlAction(0,143,true) -- disable melee
            DisableControlAction(0,75,true) -- disable exit vehicle
            DisableControlAction(27,75,true) -- disable exit vehicle
            DisableControlAction(0,22,true) -- disable jump
            DisableControlAction(0,32,true) -- disable move up
            DisableControlAction(0,268,true)
            DisableControlAction(0,33,true) -- disable move down
            DisableControlAction(0,269,true)
            DisableControlAction(0,34,true) -- disable move left
            DisableControlAction(0,270,true)
            DisableControlAction(0,35,true) -- disable move right
            DisableControlAction(0,271,true)
        end
    end
end)

-- FOLLOW

local follow_player

-- follow another player
-- player: nil to disable
function tzRP.followPlayer(player)
    follow_player = player

    if not player then -- unfollow
        ClearPedTasks(GetPlayerPed(-1))
    end
end

-- return player or nil if not following anyone
function tzRP.getFollowedPlayer()
    return follow_player
end

-- follow thread
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(5000)
        if follow_player then
            local tplayer = GetPlayerFromServerId(follow_player)
            local ped = GetPlayerPed(-1)
            if NetworkIsPlayerConnected(tplayer) then
                local tped = GetPlayerPed(tplayer)
                TaskGoToEntity(ped, tped, -1, 1.0, 10.0, 1073741824.0, 0)
                SetPedKeepTask(ped, true)
            end
        end
    end
end)

-- JAIL

local jail = nil

-- jail the player in a no-top no-bottom cylinder
function tzRP.jail(x,y,z,radius)
    tzRP.teleport(x,y,z) -- teleport to center
    jail = {x+0.0001,y+0.0001,z+0.0001,radius+0.0001}
end

-- unjail the player
function tzRP.unjail()
    jail = nil
end

function tzRP.isJailed()
    return jail ~= nil
end

-- jail thread
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(5)
        if jail then
            local x,y,z = tzRP.getPosition()

            local dx = x-jail[1]
            local dy = y-jail[2]
            local dist = math.sqrt(dx*dx+dy*dy)

            if dist >= jail[4] then
                local ped = GetPlayerPed(-1)
                SetEntityVelocity(ped, 0.0001, 0.0001, 0.0001) -- stop player

                -- normalize + push to the edge + add origin
                dx = dx/dist*jail[4]+jail[1]
                dy = dy/dist*jail[4]+jail[2]

                -- teleport player at the edge
                SetEntityCoordsNoOffset(ped,dx,dy,z,true,true,true)
            end
        end
    end
end)

-- WANTED

-- wanted level sync
local wanted_level = 0

function tzRP.applyWantedLevel(new_wanted)
    Citizen.CreateThread(function()
        local old_wanted = GetPlayerWantedLevel(PlayerId())
        local wanted = math.max(old_wanted,new_wanted)
        ClearPlayerWantedLevel(PlayerId())
        SetPlayerWantedLevelNow(PlayerId(),false)
        Citizen.Wait(10)
        SetPlayerWantedLevel(PlayerId(),wanted,false)
        SetPlayerWantedLevelNow(PlayerId(),false)
    end)
end

-- update wanted level
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(2000)

        -- if cop, reset wanted level
        if cop then
            ClearPlayerWantedLevel(PlayerId())
            SetPlayerWantedLevelNow(PlayerId(),false)
        end

        -- update level
        local nwanted_level = GetPlayerWantedLevel(PlayerId())
        if nwanted_level ~= wanted_level then
            wanted_level = nwanted_level
            zRPserver._updateWantedLevel(wanted_level)
        end
    end
end)

-- detect vehicle stealing
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1)
        local ped = GetPlayerPed(-1)
        if IsPedTryingToEnterALockedVehicle(ped) or IsPedJacking(ped) then
            Citizen.Wait(2000) -- wait x seconds before setting wanted
            local ok,vtype,name = tzRP.getNearestOwnedVehicle(5)
            if not ok then -- prevent stealing detection on owned vehicle
                for i=0,4 do -- keep wanted for 1 minutes 30 seconds
                    tzRP.applyWantedLevel(2)
                    Citizen.Wait(15000)
                end
            end
            Citizen.Wait(15000) -- wait 15 seconds before checking again
        end
    end
end)

-- Police Drag
local other = nil
local drag = nil
local playerStillDragged = false


function tzRP.policeDrag(p1)
    other = p1
    drag = not drag
end


Citizen.CreateThread(function()
    while true do
        if drag and other then
            local ped = GetPlayerPed(GetPlayerFromServerId(other))
            local myped = GetPlayerPed(-1)
            Citizen.InvokeNative(0x6B9BBD38AB0796DF, myped, ped, 4103, 11816, 0.50, 0.0, 0.1, 0.0, 0.0, 0.0, false, false, false, false, 2, true)
            playerStillDragged = true
        else
            if playerStillDragged then
                DetachEntity(GetPlayerPed(-1), true, false)
                playerStillDragged = false
            end
        end
        Citizen.Wait(0)
    end
end)

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
        local ped = GetPlayerPed(-1)
        local veh = GetVehiclePedIsIn(ped, false)
        local vehCoord = GetEntityCoords(veh)
        if IsPedInAnyVehicle(ped, false) then
            if DoesObjectOfTypeExistAtCoords(vehCoord["x"], vehCoord["y"], vehCoord["z"], 0.9, GetHashKey("P_ld_stinger_s"), true) then
                SetVehicleTyreBurst(veh, 0, true, 1000.0)
                SetVehicleTyreBurst(veh, 1, true, 1000.0)
                SetVehicleTyreBurst(veh, 2, true, 1000.0)
                SetVehicleTyreBurst(veh, 3, true, 1000.0)
                SetVehicleTyreBurst(veh, 4, true, 1000.0)
                SetVehicleTyreBurst(veh, 5, true, 1000.0)
                SetVehicleTyreBurst(veh, 6, true, 1000.0)
                SetVehicleTyreBurst(veh, 7, true, 1000.0)
                tzRP.removeSpikes()
            end
        end
    end
end)

