---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 8:12 PM
---

zRP.prepare("zRP/init_characters_table",[[
CREATE TABLE IF NOT EXISTS zrp_characters(
  id INTEGER AUTO_INCREMENT,
  user_id VARCHAR(36),
  CONSTRAINT pk_characters PRIMARY KEY(id),
  CONSTRAINT fk_characters_users FOREIGN KEY(user_id) REFERENCES zrp_users(id) ON DELETE CASCADE
);]])

zRP.prepare("zRP/getcharacters_byuser","SELECT id FROM zrp_characters WHERE user_id = @user_id")
zRP.prepare("zRP/create_new_character","INSERT INTO zrp_characters(user_id) VALUES(@user_id); SELECT LAST_INSERT_ID() AS id")


zRP.prepare("zRP/init_user_data",[[
CREATE TABLE IF NOT EXISTS zrp_user_data(
  character_id INTEGER,
  dkey VARCHAR(100),
  dvalue TEXT,
  CONSTRAINT pk_character_data PRIMARY KEY(character_id,dkey),
  CONSTRAINT fk_user_data_users FOREIGN KEY(user_id) REFERENCES zrp_users(id) ON DELETE CASCADE
);]])


zRP.prepare("zRP/set_characterdata","REPLACE INTO zrp_character_data(character_id,dkey,dvalue) VALUES(@character_id,@key,@value)")
zRP.prepare("zRP/get_characterdata","SELECT dvalue FROM zrp_character_data WHERE character_id = @character_id AND dkey = @key")