---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 9:04 PM
---

-- sql

zRP.prepare("zRP/home_tables", [[
CREATE TABLE IF NOT EXISTS zrp_user_homes(
  user_id INTEGER,
  home VARCHAR(100),
  number INTEGER,
  CONSTRAINT pk_user_homes PRIMARY KEY(user_id),
  CONSTRAINT fk_user_homes_users FOREIGN KEY(user_id) REFERENCES zrp_users(id) ON DELETE CASCADE,
  UNIQUE(home,number)
);
]])
zRPBase.tables[5] = "zRP/home_tables"

zRP.prepare("zRP/get_address","SELECT home, number FROM zrp_user_homes WHERE user_id = @user_id")
zRP.prepare("zRP/get_home_owner","SELECT user_id FROM zrp_user_homes WHERE home = @home AND number = @number")
zRP.prepare("zRP/rm_address","DELETE FROM zrp_user_homes WHERE user_id = @user_id")
zRP.prepare("zRP/set_address","REPLACE INTO zrp_user_homes(user_id,home,number) VALUES(@user_id,@home,@number)")
