---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:54 PM
---

-- ping timeout
function task_timeout()
    local users = zRP.getUsers()
    for k,v in pairs(users) do
        if GetPlayerPing(v) <= 0 then
            zRP.kick(v,"[zRP] Ping timeout.")
            zRP.dropPlayer(v)
        end
    end

    SetTimeout(30000, task_timeout)
end
task_timeout()
