---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 2:16 PM
---
RegisterServerEvent("zRPcli:playerSpawned")  -- Link to Handler

RegisterServerEvent("zRP:playerDied")
