---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:46 PM
---


function zRP.setSData(key,value,id)
    if not id then
        id = "main"
    end
    zRP.execute("zRP/set_srvdata", {id = id, key = key, value = value})
end

function zRP.getSData(key, cbr)
    local rows = zRP.query("zRP/get_srvdata", {key = key})
    if #rows > 0 then
        return rows[1].dvalue
    else
        return ""
    end
end

-- return map of user_id -> player source
function zRP.getUsers()
    local users = {}
    for k,v in pairs(zRP.user_sources) do
        users[k] = v
    end

    return users
end

function zRP.ban(source,reason)
    local user_id = zRP.getUserId(source)

    if user_id then
        zRP.setBanned(user_id,true)
        zRP.kick(source,"[Banned] "..reason)
    end
end

function zRP.banUser(user_id, reason)
    local source = zRP.getUserSource(user_id)
    zRP.setBanned(user_id,true)
    if source then
        zRP.kick(source,"[Banned] " ..reason)
    end
end

function zRP.kick(source,reason)
    DropPlayer(source,reason)
end

--[[ --TODO Systema de Character
function zRP.kickCharacter(character_id, reason)
    local source = zRP.getCharacterSource(character_id)
    DropPlayer(source,reason)
end
--]]

function zRP.kickUser(user_id, reason)
    local source = zRP.getUserSource(user_id)
    if source then
        DropPlayer(source, reason)
    end
    return false
end

-- drop zRP player/user (internal usage)
function zRP.dropPlayer(source)
    local user_id = zRP.getUserId(source)
    local endpoint = zRP.getPlayerEndpoint(source)

    -- remove player from connected clients
    zRPclient._removePlayer(-1, source)

    if user_id then
        TriggerEvent("zRP:playerLeave", user_id, source)

        -- save user data table
        zRP.setUData(user_id,"zRP:datatable",json.encode(zRP.getUserDataTable(user_id)))

        print("[zRP] "..endpoint.." disconnected (user_id = "..user_id..")")
        zRP.users[zRP.rusers[user_id]] = nil
        zRP.rusers[user_id] = nil
        zRP.user_tables[user_id] = nil
        zRP.user_tmp_tables[user_id] = nil
        zRP.user_sources[user_id] = nil
    end
end
