---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:53 PM
---

local config = zRPBase.config
-- tasks

function task_save_datatables()
    SetTimeout(config.save_interval*1000, task_save_datatables)
    TriggerEvent("zRP:save")

    Debug.log("save datatables")
    for k,v in pairs(zRP.user_tables) do
        zRP.setUData(k,"zRP:datatable",json.encode(v))
    end
end

async(function()
    task_save_datatables()
end)

-- init tables
print("[zRP] init base tables")
async(function()
    for k,v in pairs(zRPBase.tables) do
        zRP.execute(v)
    end
end)