---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:28 PM
---

-- queries

local server_base = module("zRP_base_extensions/DB/Server/Base")  -- 0
local user_base = module("zRP_base_extensions/DB/User/Base") --1,2,3
local character_identity = module("zRP_base_extensions/DB/Character/identity") --4
local character_home = module("zRP_base_extensions/DB/Character/home") --5
local character_money = module("zRP_base_extensions/DB/Economy/money") -- 6
local economy_business = module("zRP_base_extensions/DB/Economy/business") -- 7
local store = module("zRP_base_extensions/DB/Shop/store") -- 8
