---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:28 PM
---

-- queries
zRP.prepare("zRP/base_tables",[[
CREATE TABLE IF NOT EXISTS zrp_users(
  id INTEGER AUTO_INCREMENT,
  last_login VARCHAR(255),
  whitelisted BOOLEAN,
  banned BOOLEAN,
  CONSTRAINT pk_user PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS zrp_user_ids(
  identifier VARCHAR(100),
  user_id INTEGER,
  CONSTRAINT pk_user_ids PRIMARY KEY(identifier),
  CONSTRAINT fk_user_ids_users FOREIGN KEY(user_id) REFERENCES zrp_users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS zrp_user_data(
  user_id INTEGER,
  dkey VARCHAR(100),
  dvalue TEXT,
  CONSTRAINT pk_user_data PRIMARY KEY(user_id,dkey),
  CONSTRAINT fk_user_data_users FOREIGN KEY(user_id) REFERENCES zrp_users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS zrp_srv_data(
  dkey VARCHAR(100),
  dvalue TEXT,
  CONSTRAINT pk_srv_data PRIMARY KEY(dkey)
);
]])

zRP.prepare("zRP/create_user","INSERT INTO zrp_users(whitelisted,banned) VALUES(false,false); SELECT LAST_INSERT_ID() AS id")
zRP.prepare("zRP/add_identifier","INSERT INTO zrp_user_ids(identifier,user_id) VALUES(@identifier,@user_id)")
zRP.prepare("zRP/userid_byidentifier","SELECT user_id FROM zrp_user_ids WHERE identifier = @identifier")

zRP.prepare("zRP/set_userdata","REPLACE INTO zrp_user_data(user_id,dkey,dvalue) VALUES(@user_id,@key,@value)")
zRP.prepare("zRP/get_userdata","SELECT dvalue FROM zrp_user_data WHERE user_id = @user_id AND dkey = @key")

zRP.prepare("zRP/set_srvdata","REPLACE INTO zrp_srv_data(dkey,dvalue) VALUES(@key,@value)")
zRP.prepare("zRP/get_srvdata","SELECT dvalue FROM zrp_srv_data WHERE dkey = @key")

zRP.prepare("zRP/get_banned","SELECT banned FROM zrp_users WHERE id = @user_id")
zRP.prepare("zRP/set_banned","UPDATE zrp_users SET banned = @banned WHERE id = @user_id")
zRP.prepare("zRP/get_whitelisted","SELECT whitelisted FROM zrp_users WHERE id = @user_id")
zRP.prepare("zRP/set_whitelisted","UPDATE zrp_users SET whitelisted = @whitelisted WHERE id = @user_id")
zRP.prepare("zRP/set_last_login","UPDATE zrp_users SET last_login = @last_login WHERE id = @user_id")
zRP.prepare("zRP/get_last_login","SELECT last_login FROM zrp_users WHERE id = @user_id")

