---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:03 PM
---
local Luang = module("lib/Luang")
local config = zRPBase.config

-- load language
local Lang = Luang()
Lang:loadLocale(config.lang, module("cfg/lang/" .. config.lang) or {})
zRP.lang = Lang.lang[config.lang]
