---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/4/2018 1:24 PM
---
local lang = zRP.lang.basic_menu
-- hack player

function zRPMenu.hacker_hack(player, choice)
    -- get nearest player
    local user_id = vRP.getUserId(player)
    if user_id ~= nil then
        local nplayer = vRPclient.getNearestPlayer(player,25)
        if nplayer ~= nil then
            local nuser_id = vRP.getUserId(nplayer)
            if nuser_id ~= nil then
                -- prompt number
                local nbank = vRP.getBankMoney(nuser_id)
                local amount = math.floor(nbank*0.01)
                local nvalue = nbank - amount
                if math.random(1,100) == 1 then
                    vRP.setBankMoney(nuser_id,nvalue)
                    vRPclient.notify(nplayer,lang.hacker.hacked({amount}))
                    vRP.giveInventoryItem(user_id,"dirty_money",amount,true)
                else
                    vRPclient.notify(nplayer,lang.hacker.failed.good())
                    vRPclient.notify(player,lang.hacker.failed.bad())
                end
            else
                vRPclient.notify(player,lang.common.no_player_near())
            end
        else
            vRPclient.notify(player,lang.common.no_player_near())
        end
    end
end