---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/10/2018 1:28 AM
---


local cfg = module("cfg/Modules/Jobs/paycheck")

function zRP.paycheck_giver()
    for k,v in pairs(cfg.paycheck) do
        local users = zRP.getUsersByPermission(k)
        for l,w in pairs(users) do
            local user_id = w
            local paycheck = v
            local player = zRP.getUserSource(user_id)
            if cfg.bank then
                zRP.giveBankMoney(user_id,paycheck)
            else
                zRP.giveMoney(user_id,paycheck)
            end
            zRPclient.notifyPicture(player,cfg.paycheck_picture, 9, cfg.paycheck_title_picture, false, cfg.message_paycheck..paycheck..cfg.post)
        end
    end
    SetTimeout(1000*60*cfg.minutes_paycheck, function()
        zRP.paycheck_giver()
    end)
end

async(function()
   zRP.paycheck_giver()
end)

function zRP.paycheck_taker()
    for k,v in pairs(cfg.bill) do
        local users = zRP.getUsersByPermission(k)
        for l,w in pairs(users) do
            local user_id = w
            local bill = v
            local player = zRP.getUserSource(user_id)
            local money = zRP.getBankMoney(user_id)
            if cfg.bank then
                zRP.setBankMoney(user_id,money-bill)
            else
                zRP.tryPayment(user_id,bill)
            end
            zRPclient.notifyPicture(player,cfg.bill_picture, 9, cfg.bill_title_picture, false, cfg.message_bill..bill..cfg.post)
        end
    end
    SetTimeout(1000*60*cfg.minutes_bill, function()
        zRP.paycheck_taker()
    end)
end

async(function()
    zRP.paycheck_taker()
end)