---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 7:53 PM
---

zRP.character = {} -- will store logged character (id) by first identifier
zRP.rcharacter = {} -- store the opposite of character
zRP.character_tables = {} -- character data tables (logger storage, saved to database)
zRP.character_tmp_tables = {} -- character tmp data tables (logger storage, not saved)
zRP.character_sources = {} -- character sources

----- EXTRAS
zRP.characters_user = {} -- Character User  --EX: Character_ID = USERs

zRP.character_time_table ={}