---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/2/2018 4:29 PM
---


local permlang = {
        menu = {
            admin = {
                admin_list = "player.list",
                admin_whitelist = "player.whitelist",
            }
        }
}


return permlang