---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/2/2018 3:15 PM
---

local lang = zRP.lang
----------------------------------------------------------------------------------------
zRP.registerMenuBuilder("main", function(add, data)
    local user_id = zRP.getUserId(data.player)
    if user_id then
        local choices = {}

        -- build admin menu
        choices["Admin"] = {function(player,choice)
            local menu  = zRP.buildMenu("admin", {player = player})
            menu.name = "Admin"
            menu.css={top="75px",header_color="rgba(200,0,0,0.75)"}
            menu.onclose = function(player) zRP.openMainMenu(player) end -- nest menu

            if zRP.hasPermission(user_id,"player.list") then
                menu["@User list"] = {zRPMenu.admin_list,"Show/hide user list."}
            end
            if zRP.hasPermission(user_id,"player.whitelist") then
                menu["@Whitelist user"] = {zRPMenu.admin_whitelist}
            end
            if zRP.hasPermission(user_id,"player.group.add") then
                menu["@Add group"] = {zRPMenu.admin_addgroup}
            end
            if zRP.hasPermission(user_id,"player.group.remove") then
                menu["@Remove group"] = {zRPMenu.admin_removegroup}
            end
            if zRP.hasPermission(user_id,"player.unwhitelist") then
                menu["@Un-whitelist user"] = {zRPMenu.admin_unwhitelist}
            end
            if zRP.hasPermission(user_id,"player.kick") then
                menu["@Kick"] = {zRPMenu.admin_kick}
            end
            if zRP.hasPermission(user_id,"player.ban") then
                menu["@Ban"] = {zRPMenu.admin_ban}
            end
            if zRP.hasPermission(user_id,"player.unban") then
                menu["@Unban"] = {zRPMenu.admin_unban}
            end
            if zRP.hasPermission(user_id,"player.noclip") then
                menu["@Noclip"] = {zRPMenu.admin_noclip}
            end
            if zRP.hasPermission(user_id,"player.custom_emote") then
                menu["@Custom emote"] = {zRPMenu.admin_emote}
            end
            if zRP.hasPermission(user_id,"player.custom_sound") then
                menu["@Custom sound"] = {zRPMenu.admin_sound}
            end
            if zRP.hasPermission(user_id,"player.custom_sound") then
                menu["@Custom audiosource"] = {zRPMenu.admin_audiosource}
            end
            if zRP.hasPermission(user_id,"player.coords") then
                menu["@Coords"] = {zRPMenu.admin_coords}
            end
            if zRP.hasPermission(user_id,"player.tptome") then
                menu["@TpToMe"] = {zRPMenu.admin_tptome}
            end
            if zRP.hasPermission(user_id,"player.tpto") then
                menu["@TpTo"] = {zRPMenu.admin_tpto}
            end
            if zRP.hasPermission(user_id,"player.tpto") then
                menu["@TpToCoords"] = {zRPMenu.admin_tptocoords}
            end
            if zRP.hasPermission(user_id,"player.givemoney") then
                menu["@Give money"] = {zRPMenu.admin_givemoney}
            end
            if zRP.hasPermission(user_id,"player.giveitem") then
                menu["@Give item"] = {zRPMenu.admin_giveitem}
            end
            if zRP.hasPermission(user_id,"player.display_custom") then
                menu["@Display customization"] = {zRPMenu.admin_display_custom}
            end
            if zRP.hasPermission(user_id,"player.calladmin") then
                menu["@Call admin"] = {zRPMenu.admin_calladmin}
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.deleteveh.perm()
                menu["@Delete Vehicle"] = {zRPMenu.admin_deleteveh, "Delete vehicle"} -- lang.basic_menu.deleteveh.button() -- lang.basic_menu.deleteveh.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.spawnveh.perm()
                menu["@Spawn Vehicle"] = {zRPMenu.admin_spawnveh, "Spawn Vehicle"} -- lang.basic_menu.spawnveh.button() -- lang.basic_menu.spawnveh.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.godmode.perm()
                menu["@God mode"] = {zRPMenu.admin_godmode, "God mode"} -- lang.basic_menu.godmode.button() -- lang.basic_menu.godmode.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.blips.perm()
                menu["@Blips"] = {zRPMenu.admin_blips, "Blips"} -- lang.basic_menu.blips.button() -- lang.basic_menu.blips.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.sprites.perm()
                menu["@Sprites"] = {zRPMenu.admin_sprites, "Sprites"} -- lang.basic_menu.sprites.button() -- lang.basic_menu.sprites.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.crun.perm()
                menu["@Crun"] = {zRPMenu.admin_crun, "Run client string"} -- lang.basic_menu.crun.button() -- lang.basic_menu.crun.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.srun.perm()
                menu["@Srun"] = {zRPMenu.admin_srun, "Run Server string"} -- lang.basic_menu.srun.button() -- lang.basic_menu.srun.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.tptowaypoint.perm()
                menu["@Tp to WayPoint"] = {zRPMenu.admin_tptowaypoint, "Tp to waypoint"} -- lang.basic_menu.tptowaypoint.button() -- lang.basic_menu..tptowaypoint.desc()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.unjail.perm()
                menu["@Admin unjail"] = {zRPMenu.police_unjail, lang.basic_menu.unjail.desc()} -- lang.unjail.button()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.spikes.perm()
                menu["@Admin spike"] = {zRPMenu.police_spikes, lang.basic_menu.spikes.perm()} -- lang.spikes.button()
            end
            if zRP.hasPermission(user_id,"player.kick") then -- lang.basic_menu.freeze.perm()
                menu["@Admin freeze"] = {zRPMenu.police_freeze, lang.basic_menu.freeze.perm()} -- lang.freeze.button()
            end
            zRP.openMenu(player,menu)
        end}

        add(choices)
    end
end)