---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/2/2018 5:23 PM
---
local lang = zRP.lang

zRP.registerMenuBuilder("quick_menu", function(add, data)
    local choices = {}
    local player = data.player
    local user_id = zRP.getUserId(player)
    if user_id then
        -- check if in a radio group
        local groups = zRP.getUserGroups(user_id)
        local ok = false
        for group,_ in pairs(groups) do
            local cgroups = zRPMenu.basic_radio_cgroup()
            if cgroups[group] then
                ok = true
                break
            end
        end

        if ok then
            choices[lang.radio.title()] = {function()
                if rusers[user_id] then
                    zRP.disconnectRadio(user_id)
                else
                    zRP.connectRadio(user_id)
                end
            end}
        end
    end

    add(choices)
end)
