---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/2/2018 5:09 PM
---
local lang = zRP.lang


zRP.registerMenuBuilder("main", function(add, data)
    local player = data.player
    local choices = {}
    choices[lang.phone.title()] = {function() zRP.openMenu(player,zRPMenu.basic_phone()) end}

    local user_id = zRP.getUserId(player)
    if user_id and zRP.hasPermission(user_id, "player.phone") then
        add(choices)
    end
end)

zRP.registerMenuBuilder("phone", function(add) -- phone menu is created on server start, so it has no permissions.
    Citizen.CreateThread(function()
        local choices = {} -- Comment the choices you want to disable by adding -- in front of them.
        choices[lang.basic_menu.mpay.button()] = {zRPMenu.player_mobilepay, lang.basic_menu.mpay.desc()} -- transfer money through phone
        choices[lang.basic_menu.mcharge.button()] = {zRPMenu.player_mobilecharge, lang.basic_menu.mcharge.desc()} -- charge money through phone
        add(choices)
    end)
end)
