---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/2/2018 5:09 PM
---
local lang = zRP.lang


zRP.registerMenuBuilder("main", function(add, data)
    local player = data.player
    local choices = {}
    choices[lang.phone.title()] = {function() zRP.openMenu(player,zRPMenu.basic_phone()) end}

    local user_id = zRP.getUserId(player)
    if user_id and zRP.hasPermission(user_id, "player.phone") then
        add(choices)
    end
end)
