---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/2/2018 3:15 PM
---
--TODO Unir em um builder apenas

local htmlEntities = module("lib/htmlEntities")
local lang = zRP.lang




zRP.registerMenuBuilder("main", function(add, data)
    local choices = {}
    choices[lang.emotes.title()] = {function(player, choice)
        -- build emotes menu
        local menu = {name=lang.emotes.title(),css={top="75px",header_color="rgba(0,125,255,0.75)"}}
        local user_id = zRP.getUserId(player)

        if user_id then
            -- add emotes to the emote menu
            for k,v in pairs(emotes) do
                if zRP.hasPermissions(user_id, v.permissions or {}) then
                    menu[k] = {zRPMenu.player_emote}
                end
            end
        end

        -- clear current emotes
        menu[lang.emotes.clear.title()] = {function(player,choice)
            zRPclient._stopAnim(player,true) -- upper
            zRPclient._stopAnim(player,false) -- full
        end, lang.emotes.clear.description()}

        zRP.openMenu(player,menu)
    end}
    add(choices)
end)

-- add identity to main menu
zRP.registerMenuBuilder("main", function(add, data)
    local player = data.player

    local user_id = zRP.getUserId(player)
    if user_id then
        local identity = zRP.getUserIdentity(user_id)

        if identity then
            -- generate identity content
            -- get address
            local address = zRP.getUserAddress(user_id)
            local home = ""
            local number = ""
            if address then
                home = address.home
                number = address.number
            end

            local content = lang.cityhall.menu.info({htmlEntities.encode(identity.name),htmlEntities.encode(identity.firstname),identity.age,identity.registration,identity.phone,home,number})
            local choices = {}
            choices[lang.cityhall.menu.title()] = {function()end, content}

            add(choices)
        end
    end
end)



zRP.registerMenuBuilder("main", function(add, data)
    local user_id = zRP.getUserId(data.player)
    if user_id ~= nil then
        local choices = {}

        if zRP.hasPermission(user_id,lang.fixhaircut.perm()) then
            menu[lang.fixhaircut.button()] = {zRPMenu.player_fixhair, lang.fixhaircut.desc()}-- just a work around for barbershop green hair bug while I am busy
        end

        if zRP.hasPermission(user_id,lang.userlist.perm()) then
            menu[lang.userlist.button()] = {zRPMenu.player_userlist, lang.userlist.desc()} -- a user list for players with zRP ids, player name and identity names only.
        end


--[[
        if zRP.hasPermission(user_id,lang.basic_menu.loot.perm()) then
            choices[lang.basic_menu.loot.button()] = {zRPMenu.thief_loot, lang.basic_menu.loot.desc()} -- take the items of nearest player in coma
        end
]]


        add(choices)
    end
end)

