---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/4/2018 8:06 PM
---

local lang = zRP.lang


zRP.registerMenuBuilder("police", function(add, data)
    local user_id = zRP.getUserId(data.player)
    if user_id ~= nil then
        local choices = {}

        if zRP.hasPermission(user_id,lang.basic_menu.jail.perm()) then
            choices[lang.basic_menu.jail.button()] = {zRPMenu.police_jail, lang.basic_menu.jail.desc()} -- Send a nearby handcuffed player to jail with prompt for choice and user_list
        end

        if zRP.hasPermission(user_id,lang.basic_menu.unjail.perm()) then
            choices[lang.basic_menu.unjail.button()] = {zRPMenu.police_unjail, lang.basic_menu.spikes.desc()} -- Un jails chosen player if he is jailed (Use admin.easy_unjail as permission to have this in admin menu working in non jailed players)
        end

        if zRP.hasPermission(user_id,lang.basic_menu.fine.perm()) then
            choices[lang.basic_menu.fine.button()] = {zRPMenu.police_fine, lang.basic_menu.fine.desc()} -- Fines closeby player
        end
        if zRP.hasPermission(user_id,lang.basic_menu.cuff.perm()) then
            choices[lang.basic_menu.cuff.button()] = {zRPMenu.police_handcuff, lang.basic_menu.handcuff.desc()} -- Toggle cuffs AND CLOSE MENU for nearby player
        end

        if zRP.hasPermission(user_id,lang.basic_menu.spikes.perm()) then
            choices[lang.basic_menu.spikes.button()] = {zRPMenu.police_spikes, lang.basic_menu.spikes.desc()} -- Toggle spikes
        end

        if zRP.hasPermission(user_id,lang.basic_menu.drag.perm()) then
            choices[lang.basic_menu.drag.button()] = {zRPMenu.police_drag, lang.basic_menu.drag.desc()} -- Drags closest handcuffed player
        end

        if zRP.hasPermission(user_id,lang.basic_menu.freeze.perm()) then
            choices[lang.basic_menu.freeze.button()] = {zRPMenu.police_freeze, lang.basic_menu.freeze.desc()} -- Toggle freeze
        end

        if zRP.hasPermission(user_id,lang.basic_menu.jail.perm()) then
            choices["APREENDER VEICULO"] = {zRPMenu.police_size_vehicle, "apreende"}
        end

        add(choices)
    end
end)

