---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:41 PM
---

function zRP.getPlayerEndpoint(player)
    return GetPlayerEP(player) or "0.0.0.0"
end

function zRP.getPlayerName(player)
    return GetPlayerName(player) or "unknown"
end

w