---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/8/2018 3:31 PM
---
local cfg = module("cfg/Modules/Shop/basic_barbershop")
local barbershops  = cfg.barbershops
local lang = zRP.lang

-- open the skin shop for the specified ped parts
-- name = partid
function zRP.openBarbershop(source,parts)
    local user_id = zRP.getUserId(source)
    if user_id then
        -- notify player if wearing a uniform
        local data = zRP.getUserDataTable(user_id)
        if data.cloakroom_idle ~= nil then
            zRPclient.notify(source,lang.common.wearing_uniform())
        end

        -- get old customization to compute the price
        local old_custom = zRPclient.getOverlay(source)

        -- start building menu
        local menudata = {
            name=lang.barbershop.title(),
            css={top = "75px", header_color="rgba(0,255,125,0.75)"}
        }

        local drawables = {}
        local textures = {}

        local ontexture = function(player, choice)
            -- change texture
            local texture = textures[choice]
            texture[1] = texture[1]+1
            if texture[1] >= texture[2] then texture[1] = 0 end -- circular selection

            -- apply change
            local custom = zRPclient.getOverlay(source)
            custom[""..parts[choice]] = {drawables[choice][1],texture[1]}
            zRPclient._setOverlay(source,custom)
        end

        local ondrawable = function(player, choice, mod)
            if mod == 0 then -- tex variation
                ontexture(player,choice)
            else

                -- change drawable
                local drawable = drawables[choice]
                drawable[1] = drawable[1]+mod

                if isprop then
                    if drawable[1] >= drawable[2] then drawable[1] = -1 -- circular selection (-1 for prop parts)
                    elseif drawable[1] < -1 then drawable[1] = drawable[2]-1 end
                else
                    if drawable[1] >= drawable[2] then drawable[1] = 0 -- circular selection
                    elseif drawable[1] < 0 then drawable[1] = drawable[2] end
                end

                -- apply change
                local custom = zRPclient.getOverlay(source)
                custom[""..parts[choice]] = {drawable[1],textures[choice][1]}
                zRPclient._setOverlay(source,custom)

                -- update max textures number
                local n = zRPclient.getTextures(source,drawable[1])
                textures[choice][2] = n

                if textures[choice][1] >= n then
                    textures[choice][1] = 0 -- reset texture number
                end
            end
        end

        for k,v in pairs(parts) do -- for each part, get number of drawables and build menu

            drawables[k] = {0,0} -- {current,max}
            textures[k] = {0,0}  -- {current,max}

            -- init using old customization
            local old_part = old_custom[v]
            if old_part then
                drawables[k][1] = old_part[1]
                textures[k][1] = old_part[2]
            end

            -- get max drawables
            drawables[k][2] = zRPclient.getDrawables(source,v)  -- set max

            -- get max textures for this drawable
            textures[k][2] = zRPclient.getTextures(source,v) -- set max

            -- add menu choices
            menudata[k] = {ondrawable}
        end

        menudata.onclose = function(player)
            -- compute price
            local custom = zRPclient.getOverlay(source)
            local price = 0
            for k,v in pairs(custom) do
                local old = old_custom[k]

                if v[1] ~= old[1] then price = price + cfg.drawable_change_price end -- change of drawable
                if v[2] ~= old[2] then price = price + cfg.texture_change_price end -- change of texture
            end

            if zRP.tryPayment(user_id,price) then
                if price > 0 then
                    zRPclient.notify(source,lang.money.paid({price}))
                    zRP.setUData(user_id,"zRP:barbershop",json.encode(custom))
                end
            else
                zRPclient.notify(source,lang.money.not_enough())
                -- revert changes
                zRPclient._setOverlay(source,old_custom)
            end
        end

        -- open menu
        zRP.openMenu(source,menudata)
    end
end


local function build_client_barbershops(source)
    local user_id = zRP.getUserId(source)
    if user_id ~= nil then
        for k,v in pairs(barbershops) do
            local parts,x,y,z = table.unpack(v)

            local barbershop_enter = function(source)
                zRP.openBarbershop(source,parts)
            end

            local function barbershop_leave(source)
                zRP.closeMenu(source)
            end

            zRPclient._addBlip(source,x,y,z,71,13,lang.barbershop.title())
            zRPclient._addMarker(source,x,y,z-1,0.7,0.7,0.5,0,255,125,125,150)

            zRP.setArea(source,"zRP:barbershop"..k,x,y,z,1,5,barbershop_enter,barbershop_leave)
        end
    end
end

AddEventHandler("zRP:playerSpawn",function(user_id, source, first_spawn)
    if first_spawn then
        build_client_barbershops(source)
        local custom = {}
        local value = zRP.getUData(user_id,"zRP:barbershop")
        if value ~= nil then
            custom = json.decode(value)
            zRPclient._setOverlay(source,custom)
        end
    end
end)

-- ADMIN BUTTON
local player_customs = {}

function zRPMenu.admin_display_custom(player, choice)
    local custom = zRPclient.getOverlay(player)
    if player_customs[player] then -- hide
        player_customs[player] = nil
        zRPclient.removeDiv(player,"barbershop")
    else -- show
        local content = "cfg.default = { \n"
        for k,v in pairs(custom) do
            content = content.."[\""..k.."\"] = {"..v[1]..","..v[2].."},".."\n"
        end
        content = content.."}"
        player_customs[player] = true
        local ok = zRP.prompt(player,"Head Overlay(Press CTRL+A and CTRL+C to copy):",content)
    end
end
