---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/8/2018 4:28 PM
---
local cfg = module("cfg/Modules/Shop/carwash")
local lang = zRP.lang

function zRP.cleanVehicle(source)
    local user_id = zRP.getUserId(source)
    local in_vehicle = zRPclient.isInAnyVehicle(source)
    if in_vehicle then
        local dirt = zRPclient.getDirtLevel(source)
        if parseFloat(dirt) > parseFloat(1.0) then
            local total = parseInt(parseFloat(dirt)*cfg.price)
            if zRP.tryPayment(user_id,math.floor(total)) then
                zRPclient.cleanVehicle(source)
                zRPclient.notify(source, lang.money.paid({total}))
            else
                zRPclient.notify(source, lang.money.not_enough())
            end
        else
            zRPclient.notify(source, cfg.lang.cleaned)
        end
    else
        zRPclient.notify(source, cfg.lang.no_veh)
    end
end

local function build_client_carwash(source)
    local user_id = zRP.getUserId(source)
    if user_id ~= nil then
        for k,v in pairs(cfg.carwash) do
            local x,y,z = table.unpack(v)

            local carwash_enter = function(source)
                zRP.cleanVehicle(source)
            end

            local function carwash_leave(source)
                zRPclient.notify(source,cfg.lang.goodbye)
            end

            zRPclient._addBlip(source,x,y,z,cfg.blip.id,cfg.blip.color,cfg.lang.title)
            zRPclient._addMarker(source,x,y,z-1,3,3,0.7,125,125,255,255,150)

            zRP.setArea(source,"zRP:carwash"..k,x,y,z,3,1.5,carwash_enter,carwash_leave)
        end
    end
end

AddEventHandler("zRP:playerSpawn",function(user_id, source, first_spawn)
    if first_spawn then
        build_client_carwash(source)
    end
end)