---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/19/2018 1:35 PM
---

local cfg = module("cfg/Modules/Actions/robbery")

--TODO DB

function tzRP.robbery_Over(name)
    local user_id = zRP.getUserId(source)
    zRP.giveInventoryItem(user_id,"dirty_money",cfg.robbableSpots[name].currentMoney, true )
    cfg.robbableSpots[name].currentMoney = 0
end

function zRP.robbery_OverNotification(name)
    local cops = zRP.getUsersByPermission("police.group")
    for k,v in pairs(cops) do
        local player = zRP.getUserSource(cops[k])
        TriggerClientEvent("robberies:robberyStartedNotification", player, name)      --todo trocar
    end
end

function zRP.robbery_StartedNotification(name)
    local cops = zRP.getUsersByPermission("police.group")
    for k,v in pairs(cops) do
        local player = zRP.getUserSource(cops[k])
        TriggerClientEvent("robberies:robberyStartedNotification", player, name)
    end
end

function tzRP.robbery_SyncSpots(spots)
    zRPclient.robbery_SyncSpotsClient(-1,spots)
end

function tzRP.robbery_PoliceCheck()
    local user_id = zRP.getUserId(source)
    local player = source
    local cops = zRP.getUsersByGroup("police.group")
    if zRP.hasPermission(user_id, "police.group") then
        zRPclient._notify(player,"~r~Cops can't rob banks.")
    else
        TriggerClientEvent("robberies:StartRobbery", player, cops_count)
    end
end