---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 8:26 PM
---

zRP.prepare("zRP/base_tables",[[
CREATE TABLE IF NOT EXISTS zrp_srv_data(
  id VARCHAR(100),
  dkey VARCHAR(100),
  dvalue LONGTEXT,
  CONSTRAINT pk_srv_data PRIMARY KEY(dkey)
);
]])


zRP.prepare("zRP/set_srvdata","REPLACE INTO zrp_srv_data(id,dkey,dvalue) VALUES(@id,@key,@value)")
zRP.prepare("zRP/get_srvdata","SELECT dvalue FROM zrp_srv_data WHERE dkey = @key")

