---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/15/2018 5:03 PM
---


zRP.users = {
    ["license:97450620cacad874188c4ad27549456d1570302b"] = "e9414a06-8688-45ef-a3b1-c3b18650e859"
}

zRP.rusers = {
    ["e9414a06-8688-45ef-a3b1-c3b18650e859"] = "identifier"
}

zRP.user_tables = {
    [1] = {

        ["active_character_id"] = 1,
        ["character_isLoading"] = true,
        ["character_load"] =  false,
        ["groups"] = {["superadmin"] =true,["admin"] =true,["user"] =true},

    }
}

zRP.user_tmp_tables = {

    [1] = {
        ["active_character_id"] = 1,
        ["character_isLoading"] = true,
        ["character_load"] =  false,
        ["groups"] = {["superadmin"] =true,["admin"] =true,["user"] =true},

    }
}

zRP.user_sources = {
    ["SOURCE"] = "e9414a06-8688-45ef-a3b1-c3b18650e859"
}

zRP.character_tables = {
    [1] = {
        ["thirst"] = 100,
        ["health"] =120,
        ["customization"] =  {},
        ["position"] = {["x"] =1965.4846191406,["y"] =3792.4409179688,["z"] =32.301776885986},
        ["hunger"] = 50.041731846908,
        ["weapons"] = {},
        ["inventory"] = {},
        ["gaptitudes"] = {},
        ["groups"] = {["superadmin"] =true,["admin"] =true,["user"] =true},
        ["phone_directory"] = {}
    }
}

zRP.character_tmp_tables = {
    [1] = {
        ["thirst"] = 50,
        ["health"] =50,
        ["customization"] =  {},
        ["position"] = {["x"] =1565.4846191406,["y"] =3792.4409179688,["z"] =32.301776885986},
        ["hunger"] = 59.041731846908,
        ["weapons"] = {},
        ["inventory"] = {},
        ["gaptitudes"] = {},
        ["groups"] = {["superadmin"] =true,["admin"] =true,["user"] =true},
        ["phone_directory"] = {}
    }
}

zRP.character_sources = {
    [1] = "SOURCE"
}


zRP.character_identifiers = {

}

zRP.rcharacter_identifiers = {

}

zRP.character_users = {
    [1] = "e9414a06-8688-45ef-a3b1-c3b18650e859"
}

zRP.users_character = {
    ["e9414a06-8688-45ef-a3b1-c3b18650e859"] = "1"
}

zRP.users_characters_list = {
    [1] = "e9414a06-8688-45ef-a3b1-c3b18650e859", -- AO CONTRARIO
}

--TODO GUARDAR INFOS DA ACOES E DESAFIOS
zRP.rp_events = {
    ["Roubo ao Banco"] = {
            ["Quinta Avenidade"] = {
                player_in_action = {4},
                player_in_action_id = {ids},
                require_to_start = 2
            }
    }
}