---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/11/2018 2:15 PM
---

zRP = {}
zRP.stores = {
    ["id"] = {
        name = "Default_Name",
        dbmanager = true,
        items = {},
        forsale = true,
        store_level = 10,
        group_store = false,
        -- owner_id = 1, -- Only For create a store with owner
        -- group = "TAXI"
        rent = false,
        buy = true,
        price = 100000,
        --seller = id,
        --time = 10
    }
}

print(zRP.stores)