---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 1/17/2019 6:24 PM
---


local cfg = {}


cfg.table = {
    ["Brasil"] = {
        ["Comercial e Servicos e Outras"] = 0,
        ["Consumo Proprio"] = 0,
        ["Iluminacao Publica"] = 0,
        ["Industrial"] = 0,
        ["Poder Publico"] = 0,
        ["Residencial"] = 0,
        ["Rural"] = 0,
        ["Rural Aquicultor"] = 0,
        ["Rural Irrigante"] = 0,
        ["Servico Publico (Agua, esgoto e saneamento)"] = 0,
        ["Servico Publico (tracao eletrica)"] = 0,
        ["Total por Regiao"] = 0
    },
    ["Sul"] = {
        ["Comercial e Servicos e Outras"] = 0,
        ["Consumo Proprio"] = 0,
        ["Iluminacao Publica"] = 0,
        ["Industrial"] = 0,
        ["Poder Publico"] = 0,
        ["Residencial"] = 0,
        ["Rural"] = 0,
        ["Rural Aquicultor"] = 0,
        ["Rural Irrigante"] = 0,
        ["Servico Publico (Agua, esgoto e saneamento)"] = 0,
        ["Servico Publico (tracao eletrica)"] = 0,
        ["Total por Regiao"] = 0
    },
    ["Sudeste"] = {
        ["Comercial e Servicos e Outras"] = 0,
        ["Consumo Proprio"] = 0,
        ["Iluminacao Publica"] = 0,
        ["Industrial"] = 0,
        ["Poder Publico"] = 0,
        ["Residencial"] = 0,
        ["Rural"] = 0,
        ["Rural Aquicultor"] = 0,
        ["Rural Irrigante"] = 0,
        ["Servico Publico (Agua, esgoto e saneamento)"] = 0,
        ["Servico Publico (tracao eletrica)"] = 0,
        ["Total por Regiao"] = 0
    },
    ["Norte"] = {
        ["Comercial e Servicos e Outras"] = 0,
        ["Consumo Proprio"] = 0,
        ["Iluminacao Publica"] = 0,
        ["Industrial"] = 0,
        ["Poder Publico"] = 0,
        ["Residencial"] = 0,
        ["Rural"] = 0,
        ["Rural Aquicultor"] = 0,
        ["Rural Irrigante"] = 0,
        ["Servico Publico (Agua, esgoto e saneamento)"] = 0,
        ["Servico Publico (tracao eletrica)"] = 0,
        ["Total por Regiao"] = 0
    },
    ["Nordeste"] = {
        ["Comercial e Servicos e Outras"] = 0,
        ["Consumo Proprio"] = 0,
        ["Iluminacao Publica"] = 0,
        ["Industrial"] = 0,
        ["Poder Publico"] = 0,
        ["Residencial"] = 0,
        ["Rural"] = 0,
        ["Rural Aquicultor"] = 0,
        ["Rural Irrigante"] = 0,
        ["Servico Publico (Agua, esgoto e saneamento)"] = 0,
        ["Servico Publico (tracao eletrica)"] = 0,
        ["Total por Regiao"] = 0
    },
    ["Centro-Oeste"] = {
        ["Comercial e Servicos e Outras"] = 0,
        ["Consumo Proprio"] = 0,
        ["Iluminacao Publica"] = 0,
        ["Industrial"] = 0,
        ["Poder Publico"] = 0,
        ["Residencial"] = 0,
        ["Rural"] = 0,
        ["Rural Aquicultor"] = 0,
        ["Rural Irrigante"] = 0,
        ["Servico Publico (Agua, esgoto e saneamento)"] = 0,
        ["Servico Publico (tracao eletrica)"] = 0,
        ["Total por Regiao"] = 0
    }
}




return cfg
