---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:30 PM
---
local config = zRPBase.config

-- return user id or nil in case of error (if not found, will create it)
function zRP.getUserIdByIdentifiers(ids)
    if ids and #ids then
        -- search identifiers
        for i=1,#ids do
            if not config.ignore_ip_identifier or (string.find(ids[i], "ip:") == nil) then  -- ignore ip identifier
                local rows = zRP.query("zRP/userid_byidentifier", {identifier = ids[i]})
                if #rows > 0 then  -- found
                    return rows[1].user_id
                end
            end
        end

        -- no ids found, create user
        local rows, affected = zRP.query("zRP/create_user", {})

        if #rows > 0 then
            local user_id = rows[1].id
            -- add identifiers
            for l,w in pairs(ids) do
                if not config.ignore_ip_identifier or (string.find(w, "ip:") == nil) then  -- ignore ip identifier
                    zRP.execute("zRP/add_identifier", {user_id = user_id, identifier = w})
                end
            end

            return user_id
        end
    end
end

-- return identification string for the source (used for non zRP identifications, for rejected players)
function zRP.getSourceIdKey(source)
    local ids = GetPlayerIdentifiers(source)
    local idk = "idk_"
    for k,v in pairs(ids) do
        idk = idk..v
    end

    return idk
end
