---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:11 PM
---
---
zRP.users = {} -- will store logged users (id) by first identifier
zRP.rusers = {} -- store the opposite of users
zRP.user_tables = {} -- user data tables (logger storage, saved to database)
zRP.user_tmp_tables = {} -- user tmp data tables (logger storage, not saved)
zRP.user_sources = {} -- user sources

----EXTRAS

zRP.users_character = {} -- User active character  -> Ex: User_id = Character_id

zRP.users_characters_list = {} -- List of User Character ->

zRP.users_loader = {}