---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 1:30 PM
---
local config = zRPBase.config

-- return user id or nil in case of error (if not found, will create it)
function zRP.getUserIdByIdentifiers(ids)
    if ids and #ids then
        -- search identifiers
        for i = 1, #ids do
            if not config.ignore_ip_identifier or (string.find(ids[i], "ip:") == nil) then
                -- ignore ip identifier
                local rows = zRP.query("zRP/userid_byidentifier", { identifier = ids[i] })
                if #rows > 0 then
                    -- found
                    return rows[1].user_id
                end
            end
        end

        -- no ids found, create user
        local rows, affected = zRP.query("zRP/create_user", {})

        if #rows > 0 then
            local user_id = rows[1].id
            -- add identifiers
            for l, w in pairs(ids) do
                if not config.ignore_ip_identifier or (string.find(w, "ip:") == nil) then
                    -- ignore ip identifier
                    zRP.execute("zRP/add_identifier", { user_id = user_id, identifier = w })
                end
            end

            return user_id
        end
    end
end

-- return identification string for the source (used for non zRP identifications, for rejected players)
function zRP.getSourceIdKey(source)
    local ids = GetPlayerIdentifiers(source)
    local idk = "idk_"
    for k, v in pairs(ids) do
        idk = idk .. v
    end

    return idk
end

--- sql
function zRP.isBanned(user_id, cbr)
    local rows = zRP.query("zRP/get_banned", { user_id = user_id })
    if #rows > 0 then
        return rows[1].banned
    else
        return false
    end
end

--- sql
function zRP.setBanned(user_id, banned)
    zRP.execute("zRP/set_banned", { user_id = user_id, banned = banned })
end

--- sql
function zRP.isWhitelisted(user_id, cbr)
    local rows = zRP.query("zRP/get_whitelisted", { user_id = user_id })
    if #rows > 0 then
        return rows[1].whitelisted
    else
        return false
    end
end

--- sql
function zRP.setWhitelisted(user_id, whitelisted)
    zRP.execute("zRP/set_whitelisted", { user_id = user_id, whitelisted = whitelisted })
end

--- sql
function zRP.getLastLogin(user_id, cbr)
    local rows = zRP.query("zRP/get_last_login", { user_id = user_id })
    if #rows > 0 then
        return rows[1].last_login
    else
        return ""
    end
end

function zRP.setUData(user_id, key, value)
    zRP.execute("zRP/set_userdata", { user_id = user_id, key = key, value = value })
end

function zRP.getUData(user_id, key, cbr)
    local rows = zRP.query("zRP/get_userdata", { user_id = user_id, key = key })
    if #rows > 0 then
        return rows[1].dvalue
    else
        return ""
    end
end

-- return user data table for zRP internal persistant connected user storage
function zRP.getUserDataTable(user_id)
    return zRP.user_tables[user_id]
end

function zRP.getUserTmpTable(user_id)
    return zRP.user_tmp_tables[user_id]
end

-- return the player spawn count (0 = not spawned, 1 = first spawn, ...)
function zRP.getSpawns(user_id)
    local tmp = zRP.getUserTmpTable(user_id)
    if tmp then
        return tmp.spawns or 0
    end

    return 0
end

function zRP.getUserId(source)
    if source ~= nil then
        local ids = GetPlayerIdentifiers(source)
        if ids ~= nil and #ids > 0 then
            return zRP.users[ids[1]]
        end
    end

    return nil
end

-- return source or nil
function zRP.getUserSource(user_id)
    return zRP.user_sources[user_id]
end
