---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 2:17 PM
---

local playerConnecting = module("zRP_base_extensions/Server/Handlers/playerConnecting")

local playerDropped  = module("zRP_base_extensions/Server/Handlers/playerDropped")

local zRPCli_playerSpawned_handler  = module("zRP_base_extensions/Server/Handlers/zRPCli_playerSpawned")

local zRP_UUID_generate_handler  = module("zRP_base_extensions/Server/Handlers/zRP-UUID_GENERATE")

local zRP_CharacterLoad = module("zRP_base_extensions/Server/Handlers/zRP_CharacterLoad")