---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 2:19 PM
---

AddEventHandler("playerDropped",function(reason)
    local source = source
    Debug.log("playerDropped "..source)

    zRP.dropPlayer(source)
end)

