---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/18/2018 11:40 AM
---
RegisterServerEvent("zRP:UUID_GENERATE")

function zRP.generateUUID()
    local uuid = "VAZIO"
    AddEventHandler("zRP:UUID_GENERATE", function(UUID)
        uuid = UUID
    end)
    TriggerEvent("zRP:UUID_GENERATOR")
    return uuid --uuid
end