---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/20/2018 5:16 AM
---

--todo implementacao

--[[
AddEventHandler("zRP:characterLoad", function(user_id, source, name, tmpdata,ids, character_id, deferrals)
    deferrals.update("[zRP] Loading Character...")
    if character_id then
        local characterdata = zRP.getCharacterData(character_id, "zRP:datatable")
        zRP.character[ids[1]]--[[ = character_id
        zRP.rcharacter[character_id] = ids[1]
        zRP.character_users[character_id] = user_id
        zRP.users_character[user_id] = character_id
        zRP.character_tmp_tables = {}
        zRP.character_tables = {}
        zRP.character_sources[character_id] = source
        zRP.character_time_table = {}
        zRP.users_loader[user_id] = {character_data = true}

        -- trigger join
        print("[zRP] "..name.." ("..zRP.getPlayerEndpoint(source)..") joined (user_id = "..user_id..") with character_id  = "..character_id..")")
        TriggerEvent("zRP:playerJoin", user_id, source, name, tmpdata.last_login)
        TriggerEvent("zRP:characterJoin", user_id, source,name, tmpdata.last_login)
    else
        deferrals.update("Character nao encontrado")
    end


end)


AddEventHandler("zRP:characterReLoad")]]


function zRP.LoadCharacter(user_id, source, character_id)
    if character_id then
        local characterdata = zRP.getCData(character_id, "zRP:datatable")
        zRP.character[ids[1]] = character_id
        zRP.rcharacter[character_id] = ids[1]
        zRP.character_users[character_id] = user_id
        zRP.users_character[user_id] = character_id
        zRP.character_tmp_tables = {}
        zRP.character_tables = {}
        zRP.character_sources[character_id] = source
        zRP.character_time_table = {}
        zRP.users_loader[user_id] = {character_data = true}

        local data = json.decode(characterdata)
        if type(data) == "table" then zRP.character_tables[character_id] = data end
        TriggerEvent("zRP:characterJoin", user_id, source,character_id)
    else
        zRP.kick(source, "Character not Found!")
    end
end