---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 2:19 PM
---
local Tunnel = module("lib/Tunnel")
local config = zRPBase.config

AddEventHandler("zRPcli:playerSpawned", function()
    Debug.log("playerSpawned "..source)
    -- register user sources and then set first spawn to false
    local user_id = zRP.getUserId(source)  --todo analisar se isso tem que ser trocado para character
    local player = source
    if user_id then
        local characters_list = zRP.getCharactersIdsByUser(user_id)
        local character_id = zRP.getCharacterActiveId(user_id, characters_list)
        zRP.LoadCharacter(user_id, source, character_id)
        zRP.user_sources[user_id] = source
        zRP.character_sources[character_id] = source
        -- trigger character load
        zRP.user_tables[user_id]["character_isLoading"] = true --todo criar o metodo que vai gerar

        local tmp = zRP.getCharacterTmpTable(character_id) --TODO analisar se isso tem que ser trocado para character
        tmp.spawns = 0
        tmp.spawns = tmp.spawns+1
        local first_spawn = (tmp.spawns == 1)

        if first_spawn then
            -- first spawn, reference player
            -- send players to new player
            for k,v in pairs(zRP.character_sources) do
                zRPclient._addPlayer(source,v)
            end
            -- send new player to all players
            zRPclient._addPlayer(-1,source)

            -- set client tunnel delay at first spawn
            Tunnel.setDestDelay(player, config.load_delay)

            -- show loading
            zRPclient._setProgressBar(player, "zRP:loading", "botright", "Loading...", 0,0,0, 100)

            SetTimeout(2000, function()
                SetTimeout(config.load_duration*1000, function() -- set client delay to normal delay
                    Tunnel.setDestDelay(player, config.global_delay)
                    zRPclient._removeProgressBar(player,"zRP:loading")
                end)
            end)
        end

        SetTimeout(2000, function() -- trigger spawn event
            TriggerEvent("zRP:playerSpawn",user_id,player,first_spawn,character_id)
        end)
    end
end)