---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 2:19 PM
---
local Tunnel = module("lib/Tunnel")
local config = zRPBase.config

AddEventHandler("zRPcli:playerSpawned", function()
    Debug.log("playerSpawned "..source)
    -- register user sources and then set first spawn to false
    local user_id = zRP.getUserId(source)
    local player = source
    if user_id then
        zRP.user_sources[user_id] = source
        local tmp = zRP.getUserTmpTable(user_id)
        tmp.spawns = tmp.spawns+1
        local first_spawn = (tmp.spawns == 1)

        if first_spawn then
            -- first spawn, reference player
            -- send players to new player
            for k,v in pairs(zRP.user_sources) do
                zRPclient._addPlayer(source,v)
            end
            -- send new player to all players
            zRPclient._addPlayer(-1,source)

            -- set client tunnel delay at first spawn
            Tunnel.setDestDelay(player, config.load_delay)

            -- show loading
            zRPclient._setProgressBar(player, "zRP:loading", "botright", "Loading...", 0,0,0, 100)

            SetTimeout(2000, function()
                SetTimeout(config.load_duration*1000, function() -- set client delay to normal delay
                    Tunnel.setDestDelay(player, config.global_delay)
                    zRPclient._removeProgressBar(player,"zRP:loading")
                end)
            end)
        end

        SetTimeout(2000, function() -- trigger spawn event
            TriggerEvent("zRP:playerSpawn",user_id,player,first_spawn)
        end)
    end
end)