---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/15/2018 5:09 PM
---

----- CURRENCY INFOS
function zRP.getTableCurrency()
    return zRP.currency.default
end

function zRP.getTableCurrencySpecial()
    return zRP.currency.special
end

function zRP.getUSDtoBRL()
    local cur = zRP.currency.default.usd.inverseRate
    return format_num(cur,2)
end

function zRP.getBRLtoUSD()
    local cur = zRP.currency.default.usd.rate
    return format_num(cur,2)
end

function zRP.getEURtoBRL()
    local cur = zRP.currency.default.eur.inverseRate
    return  format_num(cur,2)
end

function zRP.getBRLtoEUR()
    local cur = zRP.currency.default.eur.rate
    return format_num(cur,2)
end

function zRP.getGBPtoBRL()
    local cur = zRP.currency.default.gbp.inverseRate
    return format_num(cur,2)
end

function zRP.getBRLtoGBP()
    local cur = zRP.currency.default.gbp.rate
    return format_num(cur,2)
end

function zRP.getEURtoUSD()
    local cur = zRP.currency.special.rates.USD
    return format_num(cur,2)
end

function zRP.getUSDtoEUR()
    local cur = (1/zRP.currency.special.rates.USD)
    return format_num(cur,2)
end

function zRP.getXAUGramstoEUR()
    local cur = (zRP.currency.special.rates.XAU/28.3495)*1000000
    return format_num(cur,2)
end

function zRP.getXAUGramstoBR()
    local cur = ((zRP.currency.special.rates.XAU/28.3495)*1000000)*zRP.currency.default.eur.inverseRate
    return format_num(cur,2)
end

function zRP.getXAUGramstoUSD()
    local cur = ((zRP.currency.special.rates.XAU/28.3495)*1000000)*(1/zRP.currency.special.rates.USD)
    return format_num(cur,2)
end

function zRP.getXAGGramstoEUR()
    local cur = (zRP.currency.special.rates.XAG/28.3495)*1000000
    return format_num(cur,2)
end

function zRP.getXAGGramstoBR()
    local cur = ((zRP.currency.special.rates.XAG/28.3495)*1000000)*zRP.currency.default.eur.inverseRate
    return format_num(cur,2)
end

function zRP.getXAGGramstoUSD()
    local cur = ((zRP.currency.special.rates.XAG/28.3495)*1000000)*(1/zRP.currency.special.rates.USD)
    return format_num(cur,2)
end

function zRP.getBTCtoEUR()
    local cur = (1/zRP.currency.special.rates.BTC)
    return format_num(cur,2)
end

function zRP.getBTCtoBR()
    local cur = (1/zRP.currency.special.rates.BTC)*zRP.currency.default.eur.inverseRate
    return format_num(cur,2)
end

function zRP.getBTCtoUSD()
    local cur = (1/zRP.currency.special.rates.BTC)*(1/zRP.currency.special.rates.USD)
    return format_num(cur,2)
end

function zRP.getXDRtoEUR()
    local cur = (1/zRP.currency.special.rates.XDR)
    return format_num(cur,2)
end

function zRP.getXDRtoBR()
    local cur = (1/zRP.currency.special.rates.XDR)*zRP.currency.default.eur.inverseRate
    return format_num(cur,2)
end

function zRP.getXDRtoUSD()
    local cur = (1/zRP.currency.special.rates.XDR)*(1/vRP.currency.special.rates.USD)
    return format_num(cur,2)
end
