---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 12/21/2018 5:27 PM
---


client_scripts{
    "@zrp/lib/utils.lua",
    "Player/Moviment.lua",
    "Player/weapons.lua",
}