---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Muulfz.
--- DateTime: 11/17/2018 9:03 PM
---

zRP.prepare("zRP/money_tables", [[
CREATE TABLE IF NOT EXISTS zrp_user_moneys(
  user_id INTEGER,
  wallet INTEGER,
  bank INTEGER,
  CONSTRAINT pk_user_moneys PRIMARY KEY(user_id),
  CONSTRAINT fk_user_moneys_users FOREIGN KEY(user_id) REFERENCES zrp_users(id) ON DELETE CASCADE
);
]])
zRPBase.tables[6] = "zRP/money_tables"

zRP.prepare("zRP/money_init_user","INSERT IGNORE INTO zrp_user_moneys(user_id,wallet,bank) VALUES(@user_id,@wallet,@bank)")
zRP.prepare("zRP/get_money","SELECT wallet,bank FROM zrp_user_moneys WHERE user_id = @user_id")
zRP.prepare("zRP/set_money","UPDATE zrp_user_moneys SET wallet = @wallet, bank = @bank WHERE user_id = @user_id")
